### 데이터 로딩 및 확인

In [2]:
import pandas as pd
bc_df = pd.read_csv('./data/bccard_201906.csv')
# 컬럼명 확인
print(bc_df.columns)

Index(['Unnamed: 0', 'REG_YYMM', 'MEGA_CTY_NO', 'MEGA_CTY_NM', 'CTY_RGN_NO',
       'CTY_RGN_NM', 'ADMI_CTY_NO', 'ADMI_CTY_NM', 'MAIN_BUZ_CODE',
       'MAIN_BUZ_DESC', 'TP_GRP_NO', 'TP_GRP_NM', 'TP_BUZ_NO', 'TP_BUZ_NM',
       'CSTMR_GUBUN', 'CSTMR_MEGA_CTY_NO', 'CSTMR_MEGA_CTY_NM',
       'CSTMR_CTY_RGN_NO', 'CSTMR_CTY_RGN_NM', 'SEX_CTGO_CD', 'AGE_VAL', 'FLC',
       'AMT', 'CNT'],
      dtype='object')

### 앞부분, 뒷부분, 데이터 수

In [11]:
bc_df.head().iloc[:, 1:]

,REG_YYMM,MEGA_CTY_NO,MEGA_CTY_NM,CTY_RGN_NO,CTY_RGN_NM,ADMI_CTY_NO,ADMI_CTY_NM,MAIN_BUZ_CODE,MAIN_BUZ_DESC,TP_GRP_NO,...,CSTMR_GUBUN,CSTMR_MEGA_CTY_NO,CSTMR_MEGA_CTY_NM,CSTMR_CTY_RGN_NO,CSTMR_CTY_RGN_NM,SEX_CTGO_CD,AGE_VAL,FLC,AMT,CNT
0,201906,11,서울특별시,1162,관악구,11620585,낙성대동,80,음식,80,...,내국인,11,서울특별시,1162,관악구,2,30대,2,26284804,1892
1,201906,11,서울특별시,1159,동작구,11590560,상도4동,30,생활,40,...,내국인,11,서울특별시,1165,서초구,2,20대,1,109290,18
2,201906,11,서울특별시,1162,관악구,11620595,청룡동,30,생활,83,...,내국인,11,서울특별시,1162,관악구,1,20대,1,268850,52
3,201906,11,서울특별시,1144,마포구,11440660,서교동,80,음식,80,...,내국인,11,서울특별시,1138,은평구,1,20대,1,44174450,1790
4,201906,11,서울특별시,1120,성동구,11200550,사근동,80,음식,80,...,내국인,11,서울특별시,1120,성동구,1,20대,1,60338146,3536

In [10]:
bc_df.tail().iloc[:, 1:]

,REG_YYMM,MEGA_CTY_NO,MEGA_CTY_NM,CTY_RGN_NO,CTY_RGN_NM,ADMI_CTY_NO,ADMI_CTY_NM,MAIN_BUZ_CODE,MAIN_BUZ_DESC,TP_GRP_NO,...,CSTMR_GUBUN,CSTMR_MEGA_CTY_NO,CSTMR_MEGA_CTY_NM,CSTMR_CTY_RGN_NO,CSTMR_CTY_RGN_NM,SEX_CTGO_CD,AGE_VAL,FLC,AMT,CNT
99996,201906,11,서울특별시,1165,서초구,11650520,서초2동,30,생활,40,...,내국인,43,충청북도,4311,청주시,1,50대,4,50600,10
99997,201906,11,서울특별시,1117,용산구,11170520,용산2가동,30,생활,40,...,내국인,11,서울특별시,1162,관악구,1,40대,2,38640,7
99998,201906,11,서울특별시,1156,영등포구,11560535,영등포동,30,생활,40,...,내국인,28,인천광역시,2817,미추홀구,2,30대,2,340590,15
99999,201906,11,서울특별시,1141,서대문구,11410585,신촌동,40,쇼핑,42,...,내국인,44,충청남도,4413,천안시,1,20대,2,117100,3
100000,201906,11,서울특별시,1135,노원구,11350710,상계9동,20,문화,51,...,내국인,41,경기도,4115,의정부시,1,40대,3,5227500,7

In [12]:
print(f"데이터 수 : {len(bc_df)}")

데이터 수 : 100001

### 서울시 거주/비거주 고객 비교 분석

In [18]:
seoul = bc_df[bc_df['CSTMR_MEGA_CTY_NM'] == '서울특별시']
be_seoul = bc_df[bc_df['CSTMR_MEGA_CTY_NM'] != '서울특별시']
con_seoul = pd.DataFrame(index=["서울시 거주", "서울시 비거주"], columns=["거주/비거주"])
con_seoul["고객수"] = [f"{len(seoul):,}", f"{len(be_seoul):,}"]
con_seoul[f"소비액"] = [f"{seoul['AMT'].sum():,}", f"{be_seoul['AMT'].sum():,}"]
con_seoul["이용건수"] = [f"{seoul['CNT'].sum():,}", f"{be_seoul['CNT'].sum():,}"]
con_seoul

        거주/비거주     고객수              소비액       이용건수
서울시 거주     NaN  54,150  119,663,142,676  5,542,462
서울시 비거주    NaN  45,851  146,587,135,822  4,950,200

### 편의점 소비 정보 분석

In [31]:
ganpeon = bc_df[(bc_df['CTY_RGN_NM'] == '강남구') & (bc_df['TP_BUZ_NO'] == 4010)]
data = [[f"{bc_df[bc_df['TP_BUZ_NO'] == 4010]['AMT'].sum():,}", f"{bc_df[bc_df['CTY_RGN_NM'] == '강남구']['AMT'].sum():,}", 
         f"{ganpeon['AMT'].sum():,}"]]
peon_sobi = pd.DataFrame(data,index=["소비액"], columns=["편의점", "강남구", "강남구 편의점"])
peon_sobi

               편의점             강남구      강남구 편의점
소비액  7,299,184,098  35,535,648,502  707,275,140

In [32]:
data = [[f"{ganpeon['AMT'].sum():,}", f"{ganpeon[ganpeon['CSTMR_CTY_RGN_NM'] == '강남구']['AMT'].sum():,}", f"{ganpeon[ganpeon['CSTMR_CTY_RGN_NM'] != '강남구']['AMT'].sum():,}"]]
ganpeon_sobi = pd.DataFrame(data, index=["소비액"], columns=["강남구 편의점 총액", "강남구 거주자", "강남구 비거주자"])
ganpeon_sobi

      강남구 편의점 총액      강남구 거주자     강남구 비거주자
소비액  707,275,140  288,379,890  418,895,250